# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentdock < Formula
  desc "AgentDock — Slack-driven LLM agent orchestrator"
  homepage "https://github.com/Ivantseng123/agentdock"
  version "4.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ivantseng123/agentdock/releases/download/v4.0.3/agentdock_4.0.3_darwin_amd64.tar.gz"
      sha256 "08f24a5fcbfecebca3b460c4129b0b9850dc4497f623a0b494e7f2c43a09c439"

      define_method(:install) do
        bin.install "agentdock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ivantseng123/agentdock/releases/download/v4.0.3/agentdock_4.0.3_darwin_arm64.tar.gz"
      sha256 "c0ab6d0d2d36578f563eadc8758cfdd70201f65d744a4645ae3fee6ee1daf489"

      define_method(:install) do
        bin.install "agentdock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ivantseng123/agentdock/releases/download/v4.0.3/agentdock_4.0.3_linux_amd64.tar.gz"
      sha256 "80353b934676f8c6787a887a5e60c1e55d0b0cc621f69839a640e4f8739b237c"
      define_method(:install) do
        bin.install "agentdock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ivantseng123/agentdock/releases/download/v4.0.3/agentdock_4.0.3_linux_arm64.tar.gz"
      sha256 "04abd53785b6ef4d2e3d7dc58d4dd4e5badf04e161f6afcad7daf715de043649"
      define_method(:install) do
        bin.install "agentdock"
      end
    end
  end

  test do
    system "#{bin}/agentdock", "--version"
  end
end
